In [1]:
import pandas as pd

# Melt and Pivot
## melt() — Wide to Long
The melt() method in Pandas is used to unpivot a DataFrame from wide format to long format. In other words, it takes columns that represent different variables and combines them into key-value pairs (i.e., long-form data).

In [3]:
# sample DataFrame
data = {
    'Name' : ['Aryan', 'Farid', 'Aashu'],
    'Math' : [89, 76, 93],
    'Science' : [69, 76, 89],
    'English' : [50, 78, 93],
}
df = pd.DataFrame(data)
print(df)

    Name  Math  Science  English
0  Aryan    89       69       50
1  Farid    76       76       78
2  Aashu    93       89       93

In [21]:
df_melt =df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"],var_name="Subject",value_name="Score")

In [22]:
df_melt

    Name  Subject  Score
0  Aryan     Math     89
1  Farid     Math     76
2  Aashu     Math     93
3  Aryan  Science     69
4  Farid  Science     76
5  Aashu  Science     89
6  Aryan  English     50
7  Farid  English     78
8  Aashu  English     93

# pivot() — Long to Wide
The pivot() function in Pandas is used to reshape data, specifically to turn long-format data into wide-format data. This is the reverse operation of melt().

In [23]:
df_melt.pivot_table(index = "Name", columns="Subject", values="Score")

Subject  English  Math  Science
Name
Aashu       93.0  93.0     89.0
Aryan       50.0  89.0     69.0
Farid       78.0  76.0     76.0