# Merging & Joining Data
Often, data is split across multiple tables or files. Pandas lets you combine them just like SQL — or even more flexibly!

In [2]:
import pandas as pd

In [3]:
employees = pd.DataFrame({
    "empid" : [1, 2, 3],
    "Name" : ["Aryan", "Arya", "Sanju"],
    "DeptID" : [10, 20 , 30]
})

In [4]:
departments = pd.DataFrame({
    "DeptID":[10,20,40],
    "DeptName":["Hr", "Engineering", "Marketing"]
})

In [5]:
employees

   empid   Name  DeptID
0      1  Aryan      10
1      2   Arya      20
2      3  Sanju      30

In [7]:
departments

   DeptID     DeptName
0      10           Hr
1      20  Engineering
2      40    Marketing

In [10]:
pd.merge( employees, departments, on="DeptID")# inner join

   empid   Name  DeptID     DeptName
0      1  Aryan      10           Hr
1      2   Arya      20  Engineering

In [14]:
pd.merge( employees, departments, on ="DeptID", how = "left")# left join

   empid   Name  DeptID     DeptName
0      1  Aryan      10           Hr
1      2   Arya      20  Engineering
2      3  Sanju      30          NaN

In [15]:
pd.merge(employees , departments, on="DeptID",how = "right")# right join

   empid   Name  DeptID     DeptName
0    1.0  Aryan      10           Hr
1    2.0   Arya      20  Engineering
2    NaN    NaN      40    Marketing

In [18]:
pd.merge(employees, departments , on= "DeptID", how= "outer") # outer join

   empid   Name  DeptID     DeptName
0    1.0  Aryan      10           Hr
1    2.0   Arya      20  Engineering
2    3.0  Sanju      30          NaN
3    NaN    NaN      40    Marketing

# Concatenating DataFrames
Use pd.concat() to stack datasets either vertically or horizontally.

In [31]:
df1 = pd.DataFrame({ "Name": ["ALis", "Charlie"], "Score": [344,343]})
df2 = pd.DataFrame({ "Name" : ["Bob", "david"],"Age": [344,45]})

In [32]:
df1

      Name  Score
0     ALis    344
1  Charlie    343

In [33]:
df2

    Name  Age
0    Bob  344
1  david   45

In [34]:
pd.concat([df1, df2])

      Name  Score    Age
0     ALis  344.0    NaN
1  Charlie  343.0    NaN
0      Bob    NaN  344.0
1    david    NaN   45.0

In [35]:
pd.concat([df1,df2],axis=0)

      Name  Score    Age
0     ALis  344.0    NaN
1  Charlie  343.0    NaN
0      Bob    NaN  344.0
1    david    NaN   45.0

In [36]:
pd.concat([df1,df2],axis=1)

      Name  Score   Name  Age
0     ALis    344    Bob  344
1  Charlie    343  david   45